version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins_ansible
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: remote_host
    volumes:
      - "$PWD/aws-s3.sh:/home/remote_user/script.sh"
    build:
      context: centos
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    networks:
      - net
  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins_ansible/web
    ports:
      - "80:80"
    networks:
      - net
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: 'gitlab.example.com'
    ports:
      - '8090:80'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

    networks:
        - net
networks:
  net:
